apiVersion: v2
name: decision-engine
description: TriSLA Decision Engine - Central Decision Engine
type: application
version: 1.0.0
appVersion: "1.0.0"

keywords:
  - trisla
  - decision-engine
  - sla
  - 5g
  - oran

home: https://github.com/abelisboa/TriSLA-Portal
sources:
  - https://github.com/abelisboa/TriSLA-Portal

maintainers:
  - name: Abel Lisboa
    email: abelisboa@unisinos.br

dependencies: []

