apiVersion: v1
items:
- apiVersion: v1
  kind: Endpoints
  metadata:
    creationTimestamp: "2026-01-14T00:14:57Z"
    name: kafka
    namespace: trisla
    resourceVersion: "864472782"
    uid: f43bf13c-0ff0-4cd4-87c4-f30384de20ad
  subsets:
  - addresses:
    - ip: 10.233.75.59
      nodeName: node2
      targetRef:
        kind: Pod
        name: kafka-c948b8d64-jgmz5
        namespace: trisla
        uid: b9528447-90a0-4b73-ab34-703ca38b0b7c
    ports:
    - name: kafka
      port: 9092
      protocol: TCP
- apiVersion: v1
  kind: Endpoints
  metadata:
    creationTimestamp: "2025-12-19T17:28:59Z"
    labels:
      app.kubernetes.io/component: bc-nssmf
      app.kubernetes.io/instance: trisla
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: trisla
      app.kubernetes.io/version: v3.7.29
    name: trisla-bc-nssmf
    namespace: trisla
    resourceVersion: "866080849"
    uid: 9c9cb05e-e7d1-478e-a311-bc159c90320e
  subsets:
  - addresses:
    - ip: 10.233.102.178
      nodeName: node1
      targetRef:
        kind: Pod
        name: trisla-bc-nssmf-7c8ff9c4fc-kwmqd
        namespace: trisla
        uid: b491b817-29b1-4c8a-b984-41df2858ba04
    notReadyAddresses:
    - ip: 10.233.102.150
      nodeName: node1
      targetRef:
        kind: Pod
        name: trisla-bc-nssmf-68bbbd4cb8-jg4j5
        namespace: trisla
        uid: d6d0e3ef-c1f2-4896-8c54-892887d0e624
    ports:
    - name: http
      port: 8083
      protocol: TCP
- apiVersion: v1
  kind: Endpoints
  metadata:
    creationTimestamp: "2025-12-20T15:44:06Z"
    labels:
      app: trisla-bc-nssmf
    name: trisla-bc-nssmf-metrics
    namespace: trisla
    resourceVersion: "866080850"
    uid: e7b53ed5-f26f-489e-872e-c840020ccb66
  subsets:
  - addresses:
    - ip: 10.233.102.178
      nodeName: node1
      targetRef:
        kind: Pod
        name: trisla-bc-nssmf-7c8ff9c4fc-kwmqd
        namespace: trisla
        uid: b491b817-29b1-4c8a-b984-41df2858ba04
    notReadyAddresses:
    - ip: 10.233.102.150
      nodeName: node1
      targetRef:
        kind: Pod
        name: trisla-bc-nssmf-68bbbd4cb8-jg4j5
        namespace: trisla
        uid: d6d0e3ef-c1f2-4896-8c54-892887d0e624
    ports:
    - name: metrics
      port: 8083
      protocol: TCP
- apiVersion: v1
  kind: Endpoints
  metadata:
    creationTimestamp: "2026-01-20T11:58:46Z"
    labels:
      app: besu
      app.kubernetes.io/component: trisla
      app.kubernetes.io/instance: trisla
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: trisla
      app.kubernetes.io/version: v3.7.29
      component: blockchain
    name: trisla-besu
    namespace: trisla
    resourceVersion: "866077568"
    uid: f3cfb894-d9b4-4406-84c8-47521cd06d98
  subsets:
  - addresses:
    - ip: 10.233.75.24
      nodeName: node2
      targetRef:
        kind: Pod
        name: trisla-besu-5d9454c8f8-gf8c7
        namespace: trisla
        uid: b9defbb9-e9ce-4f97-a584-490a0242152a
    ports:
    - name: p2p
      port: 30303
      protocol: TCP
    - name: rpc-ws
      port: 8546
      protocol: TCP
    - name: rpc
      port: 8545
      protocol: TCP
- apiVersion: v1
  kind: Endpoints
  metadata:
    creationTimestamp: "2025-12-19T17:28:59Z"
    labels:
      app.kubernetes.io/component: decision-engine
      app.kubernetes.io/instance: trisla
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: trisla
      app.kubernetes.io/version: v3.7.29
    name: trisla-decision-engine
    namespace: trisla
    resourceVersion: "866112975"
    uid: 015d8d81-5665-47d0-8f53-cb73ef728b59
  subsets:
  - addresses:
    - ip: 10.233.102.153
      nodeName: node1
      targetRef:
        kind: Pod
        name: trisla-decision-engine-5f6fb65c8f-bz7wt
        namespace: trisla
        uid: b6639ffd-1264-495d-829e-cec29c9f753d
    ports:
    - name: http
      port: 8082
      protocol: TCP
- apiVersion: v1
  kind: Endpoints
  metadata:
    creationTimestamp: "2025-12-20T15:44:06Z"
    labels:
      app: trisla-decision-engine
    name: trisla-decision-engine-metrics
    namespace: trisla
    resourceVersion: "866112974"
    uid: 0b283595-0ae9-4f26-b8aa-46ac7deb80a6
  subsets:
  - addresses:
    - ip: 10.233.102.153
      nodeName: node1
      targetRef:
        kind: Pod
        name: trisla-decision-engine-5f6fb65c8f-bz7wt
        namespace: trisla
        uid: b6639ffd-1264-495d-829e-cec29c9f753d
    ports:
    - name: metrics
      port: 8082
      protocol: TCP
- apiVersion: v1
  kind: Endpoints
  metadata:
    creationTimestamp: "2026-01-19T23:33:13Z"
    labels:
      app.kubernetes.io/component: ml-nsmf
      app.kubernetes.io/instance: trisla
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: trisla
      app.kubernetes.io/version: v3.7.29
    name: trisla-ml-nsmf
    namespace: trisla
    resourceVersion: "866099568"
    uid: 34e5c205-7101-4b12-a4f4-2f129367e269
  subsets:
  - addresses:
    - ip: 10.233.102.156
      nodeName: node1
      targetRef:
        kind: Pod
        name: trisla-ml-nsmf-7cbfc5f696-9hrs9
        namespace: trisla
        uid: 3edad861-cfdf-4548-9e0a-41048c9fe3d1
    ports:
    - name: http
      port: 8081
      protocol: TCP
- apiVersion: v1
  kind: Endpoints
  metadata:
    creationTimestamp: "2025-12-19T17:28:59Z"
    labels:
      app.kubernetes.io/component: nasp-adapter
      app.kubernetes.io/instance: trisla
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: trisla
      app.kubernetes.io/version: v3.7.29
    name: trisla-nasp-adapter
    namespace: trisla
    resourceVersion: "866080856"
    uid: 0b958ab2-1bb9-48d3-a4de-fe63f1928d7e
  subsets:
  - addresses:
    - ip: 10.233.102.190
      nodeName: node1
      targetRef:
        kind: Pod
        name: trisla-nasp-adapter-5688bf5f8f-x4fm2
        namespace: trisla
        uid: c7fb35d5-ade2-4304-b71c-c0c2188778b5
    notReadyAddresses:
    - ip: 10.233.102.155
      nodeName: node1
      targetRef:
        kind: Pod
        name: trisla-nasp-adapter-7c8bb45994-hfc76
        namespace: trisla
        uid: 1ca125dd-0009-431e-aec8-1eab7dcf88d2
    ports:
    - name: http
      port: 8085
      protocol: TCP
- apiVersion: v1
  kind: Endpoints
  metadata:
    creationTimestamp: "2025-12-20T17:09:55Z"
    labels:
      app: trisla-portal-backend
      app.kubernetes.io/managed-by: Helm
      component: backend
    name: trisla-portal-backend
    namespace: trisla
    resourceVersion: "865949583"
    uid: ff9afdcb-e332-42fb-b9dc-fea2146ec104
  subsets:
  - addresses:
    - ip: 10.233.75.28
      nodeName: node2
      targetRef:
        kind: Pod
        name: trisla-portal-backend-7498b598f7-hm7gw
        namespace: trisla
        uid: da0abd0e-6ff8-45cf-b083-b5cb114c5688
    ports:
    - name: http
      port: 8001
      protocol: TCP
- apiVersion: v1
  kind: Endpoints
  metadata:
    creationTimestamp: "2025-12-20T17:09:55Z"
    labels:
      app: trisla-portal-frontend
      app.kubernetes.io/managed-by: Helm
      component: frontend
    name: trisla-portal-frontend
    namespace: trisla
    resourceVersion: "865921504"
    uid: 1f4d32b3-62c0-4057-8e24-72b8e2321f2e
  subsets:
  - addresses:
    - ip: 10.233.75.12
      nodeName: node2
      targetRef:
        kind: Pod
        name: trisla-portal-frontend-7dffd67779-mql7r
        namespace: trisla
        uid: 47a49c90-7896-443c-ba78-9d105b096953
    ports:
    - name: http
      port: 80
      protocol: TCP
- apiVersion: v1
  kind: Endpoints
  metadata:
    creationTimestamp: "2025-12-19T17:28:59Z"
    labels:
      app.kubernetes.io/component: sem-csmf
      app.kubernetes.io/instance: trisla
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: trisla
      app.kubernetes.io/version: v3.7.29
    name: trisla-sem-csmf
    namespace: trisla
    resourceVersion: "866080985"
    uid: e32b11ef-7b4f-4989-b3f9-66f8eacfe01c
  subsets:
  - addresses:
    - ip: 10.233.102.164
      nodeName: node1
      targetRef:
        kind: Pod
        name: trisla-sem-csmf-95dfc79f4-zpscg
        namespace: trisla
        uid: c0408c27-c08f-41b4-8909-2f22568596b0
    ports:
    - name: http
      port: 8080
      protocol: TCP
- apiVersion: v1
  kind: Endpoints
  metadata:
    creationTimestamp: "2025-12-19T17:28:59Z"
    labels:
      app.kubernetes.io/component: sla-agent-layer
      app.kubernetes.io/instance: trisla
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: trisla
      app.kubernetes.io/version: v3.7.29
    name: trisla-sla-agent-layer
    namespace: trisla
    resourceVersion: "866081007"
    uid: 461773af-c7ef-44ce-b0ff-dd1159474bd2
  subsets:
  - addresses:
    - ip: 10.233.102.141
      nodeName: node1
      targetRef:
        kind: Pod
        name: trisla-sla-agent-layer-b8c7b6fdc-x6fbb
        namespace: trisla
        uid: 9123db48-6d51-43ca-aa2a-74e9d7c0fbcc
    ports:
    - name: http
      port: 8084
      protocol: TCP
- apiVersion: v1
  kind: Endpoints
  metadata:
    creationTimestamp: "2025-12-20T15:44:06Z"
    labels:
      app: trisla-sla-agent-layer
    name: trisla-sla-agent-metrics
    namespace: trisla
    resourceVersion: "866081002"
    uid: 31aa72ed-e8a9-4658-b732-5c5f4dcc97ee
  subsets:
  - addresses:
    - ip: 10.233.102.141
      nodeName: node1
      targetRef:
        kind: Pod
        name: trisla-sla-agent-layer-b8c7b6fdc-x6fbb
        namespace: trisla
        uid: 9123db48-6d51-43ca-aa2a-74e9d7c0fbcc
    ports:
    - name: metrics
      port: 8084
      protocol: TCP
- apiVersion: v1
  kind: Endpoints
  metadata:
    creationTimestamp: "2025-12-19T17:28:59Z"
    labels:
      app.kubernetes.io/component: ui-dashboard
      app.kubernetes.io/instance: trisla
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: trisla
      app.kubernetes.io/version: v3.7.29
    name: trisla-ui-dashboard
    namespace: trisla
    resourceVersion: "865815645"
    uid: 211ef1ab-0a40-4fef-b83f-b3c43c411b44
  subsets:
  - addresses:
    - ip: 10.233.102.149
      nodeName: node1
      targetRef:
        kind: Pod
        name: trisla-ui-dashboard-85755bf748-t9zfs
        namespace: trisla
        uid: d3e8c399-83ab-4213-9610-ed6fad6a9d99
    ports:
    - name: http
      port: 80
      protocol: TCP
kind: List
metadata:
  resourceVersion: ""
