FROM python:3.11-slim
RUN apt-get update && apt-get install -y iperf3 && rm -rf /var/lib/apt/lists/*
RUN pip install flask
COPY traffic_exporter_v3.py /traffic_exporter.py
CMD ["python", "/traffic_exporter.py"]
