version: "3.9"

services:
  api:
    build: ./apps/api
    image: ghcr.io/abelisboa/trisla-api:latest
    container_name: trisla-api
    ports:
      - "8000:8000"
    environment:
      - SEMANTIC_URL=${SEMANTIC_URL:-http://trisla-semantic:8081}
      - AI_URL=${AI_URL:-http://trisla-ai:8080}
      - BLOCKCHAIN_URL=${BLOCKCHAIN_URL:-http://trisla-blockchain:8051}
      - MONITORING_URL=${MONITORING_URL:-http://trisla-monitoring:8090}
    networks:
      - trisla-net

  ui:
    build: ./apps/ui
    image: ghcr.io/abelisboa/trisla-ui:latest
    container_name: trisla-ui
    ports:
      - "5173:80"
    depends_on:
      - api
    networks:
      - trisla-net

networks:
  trisla-net:
    driver: bridge