apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: trisla-portal
    meta.helm.sh/release-namespace: trisla
  creationTimestamp: "2025-12-20T17:09:55Z"
  labels:
    app: trisla-portal-backend
    app.kubernetes.io/managed-by: Helm
    component: backend
  name: trisla-portal-backend
  namespace: trisla
  resourceVersion: "865909157"
  uid: 580ea1da-a411-4d51-93a5-f8ce11102ec9
spec:
  clusterIP: 10.233.46.159
  clusterIPs:
  - 10.233.46.159
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    nodePort: 32002
    port: 8001
    protocol: TCP
    targetPort: 8001
  selector:
    app: trisla-portal-backend
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
