# Values para o Portal TriSLA

# Configuração do Frontend
frontend:
  image:
    repository: ghcr.io/abelisboa/trisla-portal-frontend
    tag: ''
    digest: "sha256:e05ec6b7a849f8dcaaf4732b87b4539e52e21b820e0b6de25dba254dc58fa15e"
    pullPolicy: IfNotPresent
  nodePort: 32001
  replicaCount: 1
  env:
    BACKEND_URL: "http://trisla-portal-backend:8001/api/v1"

# Configuração do Backend (PROMPT_SPORTAL_06_ID_RESOLUTION — decision_id → intent_id)
backend:
  image:
    repository: ghcr.io/abelisboa/trisla-portal-backend
    tag: ''
    digest: "sha256:5f89b5acbf332252bfec5fd0e5b0db6f249e41f698cf286fd15c59f255279492"
    pullPolicy: IfNotPresent
  nodePort: 32002
  replicaCount: 1
  env:
    SEM_CSMF_URL: "http://trisla-sem-csmf:8080"
    ML_NSMF_URL: "http://trisla-ml-nsmf:8081"
    DECISION_ENGINE_URL: "http://trisla-decision-engine:8082"
    BC_NSSMF_URL: "http://trisla-bc-nssmf:8083"
    SLA_AGENT_URL: "http://trisla-sla-agent-layer:8084"
    OTEL_SDK_DISABLED: "true"

# Configurações globais
global:
  namespace: trisla

