global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'trisla-semantic'
    static_configs:
      - targets: ['trisla-semantic-layer:8080']
  - job_name: 'trisla-ai'
    static_configs:
      - targets: ['trisla-ai-layer:8080']
  - job_name: 'trisla-integration'
    static_configs:
      - targets: ['trisla-integration-layer:8080']
