route:
  receiver: 'decision-engine-webhook'
  repeat_interval: 1m

receivers:
  - name: 'decision-engine-webhook'
    webhook_configs:
      - url: 'http://trisla-decision-engine.trisla.svc.cluster.local:8080/v1/alert'
        send_resolved: true

