apiVersion: v1
kind: Endpoints
metadata:
  creationTimestamp: "2025-12-19T17:28:59Z"
  labels:
    app.kubernetes.io/component: sem-csmf
    app.kubernetes.io/instance: trisla
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: trisla
    app.kubernetes.io/version: v3.7.29
  name: trisla-sem-csmf
  namespace: trisla
  resourceVersion: "866079794"
  uid: e32b11ef-7b4f-4989-b3f9-66f8eacfe01c
subsets:
- addresses:
  - ip: 10.233.102.161
    nodeName: node1
    targetRef:
      kind: Pod
      name: trisla-sem-csmf-74fdf6dfd-ftrbg
      namespace: trisla
      uid: 284af849-8a3d-4023-b254-89effaf63c4e
  ports:
  - name: http
    port: 8080
    protocol: TCP
