global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'trisla-api'
    static_configs:
      - targets: ['trisla-api:8000']

  - job_name: 'trisla-worker'
    static_configs:
      - targets: ['trisla-worker:8000']

  - job_name: 'hibrido-prometheus'
    metrics_path: /metrics
    static_configs:
      - targets: ['hibrido-prometheus.monitoring.svc.cluster.local:9090']
        labels:
          source: "Híbrido"

  - job_name: 'trisla-local-metrics'
    metrics_path: /metrics
    static_configs:
      - targets: ['localhost:8000']
        labels:
          source: "Local"
