apiVersion: v1
items:
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"PersistentVolumeClaim","metadata":{"annotations":{},"name":"data-kafka-broker","namespace":"trisla"},"spec":{"accessModes":["ReadWriteOnce"],"resources":{"requests":{"storage":"8Gi"}},"storageClassName":"nfs-storage"}}
      pv.kubernetes.io/bind-completed: "yes"
      pv.kubernetes.io/bound-by-controller: "yes"
      volume.beta.kubernetes.io/storage-provisioner: cluster.local/nfs-storage-nfs-subdir-external-provisioner
      volume.kubernetes.io/storage-provisioner: cluster.local/nfs-storage-nfs-subdir-external-provisioner
    creationTimestamp: "2026-01-29T14:10:44Z"
    finalizers:
    - kubernetes.io/pvc-protection
    name: data-kafka-broker
    namespace: trisla
    resourceVersion: "868323675"
    uid: b9ed32c0-379a-4b6a-b866-da9c0127f19e
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 8Gi
    storageClassName: nfs-storage
    volumeMode: Filesystem
    volumeName: pvc-b9ed32c0-379a-4b6a-b866-da9c0127f19e
  status:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 8Gi
    phase: Bound
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      pv.kubernetes.io/bind-completed: "yes"
      pv.kubernetes.io/bound-by-controller: "yes"
      volume.beta.kubernetes.io/storage-provisioner: cluster.local/nfs-storage-nfs-subdir-external-provisioner
      volume.kubernetes.io/storage-provisioner: cluster.local/nfs-storage-nfs-subdir-external-provisioner
    creationTimestamp: "2025-12-22T23:30:06Z"
    finalizers:
    - kubernetes.io/pvc-protection
    labels:
      app.kubernetes.io/component: controller-eligible
      app.kubernetes.io/instance: kafka
      app.kubernetes.io/name: kafka
      app.kubernetes.io/part-of: kafka
    name: data-kafka-controller-0
    namespace: trisla
    resourceVersion: "859084489"
    uid: 9187f819-d125-4036-a59d-7d24fc7b7c63
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 8Gi
    storageClassName: nfs-storage
    volumeMode: Filesystem
    volumeName: pvc-9187f819-d125-4036-a59d-7d24fc7b7c63
  status:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 8Gi
    phase: Bound
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      pv.kubernetes.io/bind-completed: "yes"
      pv.kubernetes.io/bound-by-controller: "yes"
      volume.beta.kubernetes.io/storage-provisioner: cluster.local/nfs-storage-nfs-subdir-external-provisioner
      volume.kubernetes.io/storage-provisioner: cluster.local/nfs-storage-nfs-subdir-external-provisioner
    creationTimestamp: "2025-12-22T23:30:06Z"
    finalizers:
    - kubernetes.io/pvc-protection
    labels:
      app.kubernetes.io/component: controller-eligible
      app.kubernetes.io/instance: kafka
      app.kubernetes.io/name: kafka
      app.kubernetes.io/part-of: kafka
    name: data-kafka-controller-1
    namespace: trisla
    resourceVersion: "859084493"
    uid: 4a0aac4d-c1f8-423d-a81e-d8a87dfd475a
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 8Gi
    storageClassName: nfs-storage
    volumeMode: Filesystem
    volumeName: pvc-4a0aac4d-c1f8-423d-a81e-d8a87dfd475a
  status:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 8Gi
    phase: Bound
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      pv.kubernetes.io/bind-completed: "yes"
      pv.kubernetes.io/bound-by-controller: "yes"
      volume.beta.kubernetes.io/storage-provisioner: cluster.local/nfs-storage-nfs-subdir-external-provisioner
      volume.kubernetes.io/storage-provisioner: cluster.local/nfs-storage-nfs-subdir-external-provisioner
    creationTimestamp: "2025-12-22T23:30:06Z"
    finalizers:
    - kubernetes.io/pvc-protection
    labels:
      app.kubernetes.io/component: controller-eligible
      app.kubernetes.io/instance: kafka
      app.kubernetes.io/name: kafka
      app.kubernetes.io/part-of: kafka
    name: data-kafka-controller-2
    namespace: trisla
    resourceVersion: "859084498"
    uid: 69ba3a16-53ae-4624-b899-961b74080211
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 8Gi
    storageClassName: nfs-storage
    volumeMode: Filesystem
    volumeName: pvc-69ba3a16-53ae-4624-b899-961b74080211
  status:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 8Gi
    phase: Bound
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      meta.helm.sh/release-name: trisla
      meta.helm.sh/release-namespace: trisla
      pv.kubernetes.io/bind-completed: "yes"
      pv.kubernetes.io/bound-by-controller: "yes"
      volume.beta.kubernetes.io/storage-provisioner: cluster.local/nfs-storage-nfs-subdir-external-provisioner
      volume.kubernetes.io/storage-provisioner: cluster.local/nfs-storage-nfs-subdir-external-provisioner
    creationTimestamp: "2026-01-31T21:00:00Z"
    finalizers:
    - kubernetes.io/pvc-protection
    labels:
      app: besu
      app.kubernetes.io/instance: trisla
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: trisla
      component: blockchain
      helm.sh/chart: trisla-3.10.0
    name: trisla-besu-data
    namespace: trisla
    resourceVersion: "872802494"
    uid: 5b8fcad0-7216-4c1c-88e8-ff0c58850411
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 10Gi
    storageClassName: nfs-storage
    volumeMode: Filesystem
    volumeName: pvc-5b8fcad0-7216-4c1c-88e8-ff0c58850411
  status:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 10Gi
    phase: Bound
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"PersistentVolumeClaim","metadata":{"annotations":{},"name":"trisla-qbft-generate-temp","namespace":"trisla"},"spec":{"accessModes":["ReadWriteOnce"],"resources":{"requests":{"storage":"1Gi"}}}}
      pv.kubernetes.io/bind-completed: "yes"
      pv.kubernetes.io/bound-by-controller: "yes"
      volume.beta.kubernetes.io/storage-provisioner: cluster.local/nfs-storage-nfs-subdir-external-provisioner
      volume.kubernetes.io/storage-provisioner: cluster.local/nfs-storage-nfs-subdir-external-provisioner
    creationTimestamp: "2026-01-31T01:13:30Z"
    finalizers:
    - kubernetes.io/pvc-protection
    name: trisla-qbft-generate-temp
    namespace: trisla
    resourceVersion: "868686381"
    uid: 91ac9a13-43a2-4b43-9ca7-f365d7aa51c9
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
    storageClassName: nfs-storage
    volumeMode: Filesystem
    volumeName: pvc-91ac9a13-43a2-4b43-9ca7-f365d7aa51c9
  status:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 1Gi
    phase: Bound
kind: List
metadata:
  resourceVersion: ""
