# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import i01_interface_pb2 as proto_dot_i01__interface__pb2


class DecisionEngineServiceStub(object):
    """Interface I-01: SEM-CSMF → Decision Engine
    Envio de metadados de NEST para decisão

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendNESTMetadata = channel.unary_unary(
                '/trisla.i01.DecisionEngineService/SendNESTMetadata',
                request_serializer=proto_dot_i01__interface__pb2.NESTMetadataRequest.SerializeToString,
                response_deserializer=proto_dot_i01__interface__pb2.NESTMetadataResponse.FromString,
                )
        self.GetDecisionStatus = channel.unary_unary(
                '/trisla.i01.DecisionEngineService/GetDecisionStatus',
                request_serializer=proto_dot_i01__interface__pb2.DecisionStatusRequest.SerializeToString,
                response_deserializer=proto_dot_i01__interface__pb2.DecisionStatusResponse.FromString,
                )


class DecisionEngineServiceServicer(object):
    """Interface I-01: SEM-CSMF → Decision Engine
    Envio de metadados de NEST para decisão

    """

    def SendNESTMetadata(self, request, context):
        """Envia metadados de NEST para o Decision Engine
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDecisionStatus(self, request, context):
        """Consulta status de decisão
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DecisionEngineServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendNESTMetadata': grpc.unary_unary_rpc_method_handler(
                    servicer.SendNESTMetadata,
                    request_deserializer=proto_dot_i01__interface__pb2.NESTMetadataRequest.FromString,
                    response_serializer=proto_dot_i01__interface__pb2.NESTMetadataResponse.SerializeToString,
            ),
            'GetDecisionStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDecisionStatus,
                    request_deserializer=proto_dot_i01__interface__pb2.DecisionStatusRequest.FromString,
                    response_serializer=proto_dot_i01__interface__pb2.DecisionStatusResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'trisla.i01.DecisionEngineService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class DecisionEngineService(object):
    """Interface I-01: SEM-CSMF → Decision Engine
    Envio de metadados de NEST para decisão

    """

    @staticmethod
    def SendNESTMetadata(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/trisla.i01.DecisionEngineService/SendNESTMetadata',
            proto_dot_i01__interface__pb2.NESTMetadataRequest.SerializeToString,
            proto_dot_i01__interface__pb2.NESTMetadataResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetDecisionStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/trisla.i01.DecisionEngineService/GetDecisionStatus',
            proto_dot_i01__interface__pb2.DecisionStatusRequest.SerializeToString,
            proto_dot_i01__interface__pb2.DecisionStatusResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
