# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/i01_interface.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19proto/i01_interface.proto\x12\ntrisla.i01\"\x84\x03\n\x13NESTMetadataRequest\x12\x11\n\tintent_id\x18\x01 \x01(\t\x12\x0f\n\x07nest_id\x18\x02 \x01(\t\x12\x11\n\ttenant_id\x18\x03 \x01(\t\x12\x14\n\x0cservice_type\x18\x04 \x01(\t\x12N\n\x10sla_requirements\x18\x05 \x03(\x0b\x32\x34.trisla.i01.NESTMetadataRequest.SlaRequirementsEntry\x12\x13\n\x0bnest_status\x18\x06 \x01(\t\x12\x11\n\ttimestamp\x18\x07 \x01(\t\x12?\n\x08metadata\x18\x08 \x03(\x0b\x32-.trisla.i01.NESTMetadataRequest.MetadataEntry\x1a\x36\n\x14SlaRequirementsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"b\n\x14NESTMetadataResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x13\n\x0b\x64\x65\x63ision_id\x18\x02 \x01(\t\x12\x0f\n\x07message\x18\x03 \x01(\t\x12\x13\n\x0bstatus_code\x18\x04 \x01(\x05\"?\n\x15\x44\x65\x63isionStatusRequest\x12\x13\n\x0b\x64\x65\x63ision_id\x18\x01 \x01(\t\x12\x11\n\tintent_id\x18\x02 \x01(\t\"\xe7\x01\n\x16\x44\x65\x63isionStatusResponse\x12\x13\n\x0b\x64\x65\x63ision_id\x18\x01 \x01(\t\x12\x11\n\tintent_id\x18\x02 \x01(\t\x12\x10\n\x08\x64\x65\x63ision\x18\x03 \x01(\t\x12\x0e\n\x06reason\x18\x04 \x01(\t\x12\x11\n\ttimestamp\x18\x05 \x01(\t\x12@\n\x07\x64\x65tails\x18\x06 \x03(\x0b\x32/.trisla.i01.DecisionStatusResponse.DetailsEntry\x1a.\n\x0c\x44\x65tailsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x32\xca\x01\n\x15\x44\x65\x63isionEngineService\x12U\n\x10SendNESTMetadata\x12\x1f.trisla.i01.NESTMetadataRequest\x1a .trisla.i01.NESTMetadataResponse\x12Z\n\x11GetDecisionStatus\x12!.trisla.i01.DecisionStatusRequest\x1a\".trisla.i01.DecisionStatusResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.i01_interface_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _NESTMETADATAREQUEST_SLAREQUIREMENTSENTRY._options = None
  _NESTMETADATAREQUEST_SLAREQUIREMENTSENTRY._serialized_options = b'8\001'
  _NESTMETADATAREQUEST_METADATAENTRY._options = None
  _NESTMETADATAREQUEST_METADATAENTRY._serialized_options = b'8\001'
  _DECISIONSTATUSRESPONSE_DETAILSENTRY._options = None
  _DECISIONSTATUSRESPONSE_DETAILSENTRY._serialized_options = b'8\001'
  _globals['_NESTMETADATAREQUEST']._serialized_start=42
  _globals['_NESTMETADATAREQUEST']._serialized_end=430
  _globals['_NESTMETADATAREQUEST_SLAREQUIREMENTSENTRY']._serialized_start=327
  _globals['_NESTMETADATAREQUEST_SLAREQUIREMENTSENTRY']._serialized_end=381
  _globals['_NESTMETADATAREQUEST_METADATAENTRY']._serialized_start=383
  _globals['_NESTMETADATAREQUEST_METADATAENTRY']._serialized_end=430
  _globals['_NESTMETADATARESPONSE']._serialized_start=432
  _globals['_NESTMETADATARESPONSE']._serialized_end=530
  _globals['_DECISIONSTATUSREQUEST']._serialized_start=532
  _globals['_DECISIONSTATUSREQUEST']._serialized_end=595
  _globals['_DECISIONSTATUSRESPONSE']._serialized_start=598
  _globals['_DECISIONSTATUSRESPONSE']._serialized_end=829
  _globals['_DECISIONSTATUSRESPONSE_DETAILSENTRY']._serialized_start=783
  _globals['_DECISIONSTATUSRESPONSE_DETAILSENTRY']._serialized_end=829
  _globals['_DECISIONENGINESERVICE']._serialized_start=832
  _globals['_DECISIONENGINESERVICE']._serialized_end=1034
# @@protoc_insertion_point(module_scope)
