apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "63"
    meta.helm.sh/release-name: trisla
    meta.helm.sh/release-namespace: trisla
  creationTimestamp: "2025-12-19T17:28:59Z"
  generation: 64
  labels:
    app.kubernetes.io/component: ml-nsmf
    app.kubernetes.io/instance: trisla
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: trisla
    app.kubernetes.io/version: v3.7.29
  name: trisla-ml-nsmf
  namespace: trisla
  resourceVersion: "866138115"
  uid: e3c81ccc-682f-4f5b-8e20-c8400be9466a
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: trisla-ml-nsmf
      app.kubernetes.io/instance: trisla
      app.kubernetes.io/name: trisla
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: "2026-01-20T14:17:36-03:00"
      creationTimestamp: null
      labels:
        app: trisla-ml-nsmf
        app.kubernetes.io/instance: trisla
        app.kubernetes.io/name: trisla
    spec:
      containers:
      - env:
        - name: TRISLA_NODE_INTERFACE
          value: my5g
        - name: TRISLA_NODE_IP
          value: 192.168.10.16
        - name: OTLP_ENDPOINT
          value: http://trisla-otel-collector:4317
        - name: KAFKA_ENABLED
          value: "true"
        - name: KAFKA_BROKERS
          value: kafka:9092
        image: ghcr.io/abelisboa/trisla-ml-nsmf:v3.7.29
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: http
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: ml-nsmf
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: http
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: "4"
            memory: 4Gi
          requests:
            cpu: "1"
            memory: 1Gi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: ghcr-secret
      nodeSelector:
        kubernetes.io/hostname: node1
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2026-01-20T12:22:11Z"
    lastUpdateTime: "2026-01-20T12:22:11Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2026-01-20T17:37:52Z"
    lastUpdateTime: "2026-01-20T17:50:04Z"
    message: ReplicaSet "trisla-ml-nsmf-65d98c9cff" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 64
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
