apiVersion: apps/v1
kind: Deployment
metadata:
  name: nwdaf
  labels:
    app.kubernetes.io/name: nwdaf
    app.kubernetes.io/instance: nwdaf
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: nwdaf
      app.kubernetes.io/instance: nwdaf
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nwdaf
        app.kubernetes.io/instance: nwdaf
    spec:
      containers:
        - name: nwdaf
          image: "ghcr.io/abelisboa/trisla-nwdaf:1.0.0"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 250m
              memory: 256Mi
