apiVersion: v1
kind: Service
metadata:
  name: trisla-sla-agent-metrics
  namespace: trisla
  labels:
    app: trisla-sla-agent-layer
spec:
  selector:
    app: trisla-sla-agent-layer
  ports:
    - name: metrics
      port: 8084
      targetPort: 8084
