apiVersion: v2
name: sla-agents
description: TriSLA SLA-Agent Layer - Federated SLA Agents
type: application
version: 1.0.0
appVersion: "1.0.0"

keywords:
  - trisla
  - sla-agents
  - monitoring
  - 5g
  - oran

home: https://github.com/abelisboa/TriSLA-Portal
sources:
  - https://github.com/abelisboa/TriSLA-Portal

maintainers:
  - name: Abel Lisboa
    email: abelisboa@unisinos.br

dependencies: []




