apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"kafka","namespace":"trisla"},"spec":{"ports":[{"name":"kafka","port":9092,"targetPort":9092}],"selector":{"app":"kafka"},"type":"ClusterIP"}}
    creationTimestamp: "2026-01-14T00:14:57Z"
    name: kafka
    namespace: trisla
    resourceVersion: "864467710"
    uid: ae92c102-7377-40bf-88a3-87a2ea014072
  spec:
    clusterIP: 10.233.43.214
    clusterIPs:
    - 10.233.43.214
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: kafka
      port: 9092
      protocol: TCP
      targetPort: 9092
    selector:
      app: kafka
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      meta.helm.sh/release-name: trisla
      meta.helm.sh/release-namespace: trisla
    creationTimestamp: "2025-12-19T17:28:59Z"
    labels:
      app.kubernetes.io/component: bc-nssmf
      app.kubernetes.io/instance: trisla
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: trisla
      app.kubernetes.io/version: v3.7.29
    name: trisla-bc-nssmf
    namespace: trisla
    resourceVersion: "866080636"
    uid: d723da61-20b3-4028-92bc-9e790001f21c
  spec:
    clusterIP: 10.233.39.215
    clusterIPs:
    - 10.233.39.215
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: http
      port: 8083
      protocol: TCP
      targetPort: http
    selector:
      app: trisla-bc-nssmf
      app.kubernetes.io/instance: trisla
      app.kubernetes.io/name: trisla
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"trisla-bc-nssmf"},"name":"trisla-bc-nssmf-metrics","namespace":"trisla"},"spec":{"ports":[{"name":"metrics","port":8083,"targetPort":8083}],"selector":{"app":"trisla-bc-nssmf"}}}
    creationTimestamp: "2025-12-20T15:44:06Z"
    labels:
      app: trisla-bc-nssmf
    name: trisla-bc-nssmf-metrics
    namespace: trisla
    resourceVersion: "858498712"
    uid: 23694068-cf59-43a7-b633-d8d8479e7041
  spec:
    clusterIP: 10.233.30.108
    clusterIPs:
    - 10.233.30.108
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: metrics
      port: 8083
      protocol: TCP
      targetPort: 8083
    selector:
      app: trisla-bc-nssmf
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      meta.helm.sh/release-name: trisla
      meta.helm.sh/release-namespace: trisla
    creationTimestamp: "2026-01-20T11:58:46Z"
    labels:
      app: besu
      app.kubernetes.io/component: trisla
      app.kubernetes.io/instance: trisla
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: trisla
      app.kubernetes.io/version: v3.7.29
      component: blockchain
    name: trisla-besu
    namespace: trisla
    resourceVersion: "866074527"
    uid: 337e6583-76e0-48d9-a8c9-6afbbd642ba3
  spec:
    clusterIP: 10.233.9.111
    clusterIPs:
    - 10.233.9.111
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: rpc
      port: 8545
      protocol: TCP
      targetPort: 8545
    - name: rpc-ws
      port: 8546
      protocol: TCP
      targetPort: 8546
    - name: p2p
      port: 30303
      protocol: TCP
      targetPort: 30303
    selector:
      app: besu
      app.kubernetes.io/instance: trisla
      app.kubernetes.io/name: trisla
      component: blockchain
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      meta.helm.sh/release-name: trisla
      meta.helm.sh/release-namespace: trisla
    creationTimestamp: "2025-12-19T17:28:59Z"
    labels:
      app.kubernetes.io/component: decision-engine
      app.kubernetes.io/instance: trisla
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: trisla
      app.kubernetes.io/version: v3.7.29
    name: trisla-decision-engine
    namespace: trisla
    resourceVersion: "866080637"
    uid: d6dcdd8c-3d8b-4abf-90e1-bd3f8c26fe36
  spec:
    clusterIP: 10.233.26.201
    clusterIPs:
    - 10.233.26.201
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: http
      port: 8082
      protocol: TCP
      targetPort: http
    selector:
      app: trisla-decision-engine
      app.kubernetes.io/instance: trisla
      app.kubernetes.io/name: trisla
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"trisla-decision-engine"},"name":"trisla-decision-engine-metrics","namespace":"trisla"},"spec":{"ports":[{"name":"metrics","port":8082,"targetPort":8082}],"selector":{"app":"trisla-decision-engine"}}}
    creationTimestamp: "2025-12-20T15:44:05Z"
    labels:
      app: trisla-decision-engine
    name: trisla-decision-engine-metrics
    namespace: trisla
    resourceVersion: "858498704"
    uid: e09a23cf-d372-49ff-ae48-9ebd9c674904
  spec:
    clusterIP: 10.233.32.162
    clusterIPs:
    - 10.233.32.162
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: metrics
      port: 8082
      protocol: TCP
      targetPort: 8082
    selector:
      app: trisla-decision-engine
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      meta.helm.sh/release-name: trisla
      meta.helm.sh/release-namespace: trisla
    creationTimestamp: "2025-12-19T17:28:59Z"
    labels:
      app.kubernetes.io/component: ml-nsmf
      app.kubernetes.io/instance: trisla
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: trisla
      app.kubernetes.io/version: v3.7.29
    name: trisla-ml-nsmf
    namespace: trisla
    resourceVersion: "866080638"
    uid: 91a20b30-8162-49d5-8efa-5817eefbe5e4
  spec:
    clusterIP: 10.233.28.209
    clusterIPs:
    - 10.233.28.209
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: http
      port: 8081
      protocol: TCP
      targetPort: 8081
    selector:
      app: trisla-ml-nsmf
      app.kubernetes.io/instance: trisla
      app.kubernetes.io/name: trisla
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      meta.helm.sh/release-name: trisla
      meta.helm.sh/release-namespace: trisla
    creationTimestamp: "2025-12-19T17:28:59Z"
    labels:
      app.kubernetes.io/component: nasp-adapter
      app.kubernetes.io/instance: trisla
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: trisla
      app.kubernetes.io/version: v3.7.29
    name: trisla-nasp-adapter
    namespace: trisla
    resourceVersion: "866080639"
    uid: aa4c984d-5ce5-4718-b9ee-3b3c607ea895
  spec:
    clusterIP: 10.233.6.35
    clusterIPs:
    - 10.233.6.35
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: http
      port: 8085
      protocol: TCP
      targetPort: http
    selector:
      app: trisla-nasp-adapter
      app.kubernetes.io/instance: trisla
      app.kubernetes.io/name: trisla
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      meta.helm.sh/release-name: trisla-portal
      meta.helm.sh/release-namespace: trisla
    creationTimestamp: "2025-12-20T17:09:55Z"
    labels:
      app: trisla-portal-backend
      app.kubernetes.io/managed-by: Helm
      component: backend
    name: trisla-portal-backend
    namespace: trisla
    resourceVersion: "865909157"
    uid: 580ea1da-a411-4d51-93a5-f8ce11102ec9
  spec:
    clusterIP: 10.233.46.159
    clusterIPs:
    - 10.233.46.159
    externalTrafficPolicy: Cluster
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: http
      nodePort: 32002
      port: 8001
      protocol: TCP
      targetPort: 8001
    selector:
      app: trisla-portal-backend
    sessionAffinity: None
    type: NodePort
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      meta.helm.sh/release-name: trisla-portal
      meta.helm.sh/release-namespace: trisla
    creationTimestamp: "2025-12-20T17:09:55Z"
    labels:
      app: trisla-portal-frontend
      app.kubernetes.io/managed-by: Helm
      component: frontend
    name: trisla-portal-frontend
    namespace: trisla
    resourceVersion: "865909158"
    uid: c4964211-c397-4c81-a476-1299ad2910c9
  spec:
    clusterIP: 10.233.19.22
    clusterIPs:
    - 10.233.19.22
    externalTrafficPolicy: Cluster
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: http
      nodePort: 32001
      port: 80
      protocol: TCP
      targetPort: 80
    selector:
      app: trisla-portal-frontend
    sessionAffinity: None
    type: NodePort
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      meta.helm.sh/release-name: trisla
      meta.helm.sh/release-namespace: trisla
    creationTimestamp: "2025-12-19T17:28:59Z"
    labels:
      app.kubernetes.io/component: sem-csmf
      app.kubernetes.io/instance: trisla
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: trisla
      app.kubernetes.io/version: v3.7.29
    name: trisla-sem-csmf
    namespace: trisla
    resourceVersion: "866080640"
    uid: b78eed2b-ec79-46e7-9606-b370556c097a
  spec:
    clusterIP: 10.233.13.160
    clusterIPs:
    - 10.233.13.160
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: http
    selector:
      app: trisla-sem-csmf
      app.kubernetes.io/instance: trisla
      app.kubernetes.io/name: trisla
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      meta.helm.sh/release-name: trisla
      meta.helm.sh/release-namespace: trisla
    creationTimestamp: "2025-12-19T17:28:59Z"
    labels:
      app.kubernetes.io/component: sla-agent-layer
      app.kubernetes.io/instance: trisla
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: trisla
      app.kubernetes.io/version: v3.7.29
    name: trisla-sla-agent-layer
    namespace: trisla
    resourceVersion: "866080641"
    uid: a952a9f9-a31e-454b-9164-f827a230a9a7
  spec:
    clusterIP: 10.233.4.83
    clusterIPs:
    - 10.233.4.83
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: http
      port: 8084
      protocol: TCP
      targetPort: http
    selector:
      app: trisla-sla-agent-layer
      app.kubernetes.io/instance: trisla
      app.kubernetes.io/name: trisla
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"trisla-sla-agent-layer"},"name":"trisla-sla-agent-metrics","namespace":"trisla"},"spec":{"ports":[{"name":"metrics","port":8084,"targetPort":8084}],"selector":{"app":"trisla-sla-agent-layer"}}}
    creationTimestamp: "2025-12-20T15:44:06Z"
    labels:
      app: trisla-sla-agent-layer
    name: trisla-sla-agent-metrics
    namespace: trisla
    resourceVersion: "858498708"
    uid: 680b9263-fbad-49ab-8a81-76d60abe5bb0
  spec:
    clusterIP: 10.233.25.234
    clusterIPs:
    - 10.233.25.234
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: metrics
      port: 8084
      protocol: TCP
      targetPort: 8084
    selector:
      app: trisla-sla-agent-layer
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      meta.helm.sh/release-name: trisla
      meta.helm.sh/release-namespace: trisla
    creationTimestamp: "2025-12-19T17:28:59Z"
    labels:
      app.kubernetes.io/component: ui-dashboard
      app.kubernetes.io/instance: trisla
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: trisla
      app.kubernetes.io/version: v3.7.29
    name: trisla-ui-dashboard
    namespace: trisla
    resourceVersion: "866080642"
    uid: 47586f1f-3cda-4525-98b7-502585c40119
  spec:
    clusterIP: 10.233.4.125
    clusterIPs:
    - 10.233.4.125
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
    selector:
      app: trisla-ui-dashboard
      app.kubernetes.io/instance: trisla
      app.kubernetes.io/name: trisla
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
kind: List
metadata:
  resourceVersion: ""
