apiVersion: v1
kind: Endpoints
metadata:
  creationTimestamp: "2026-01-19T23:33:13Z"
  labels:
    app.kubernetes.io/component: ml-nsmf
    app.kubernetes.io/instance: trisla
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: trisla
    app.kubernetes.io/version: v3.7.29
  name: trisla-ml-nsmf
  namespace: trisla
  resourceVersion: "866079179"
  uid: 34e5c205-7101-4b12-a4f4-2f129367e269
subsets:
- addresses:
  - ip: 10.233.102.150
    nodeName: node1
    targetRef:
      kind: Pod
      name: trisla-ml-nsmf-79d68dc4c5-48prv
      namespace: trisla
      uid: 2f38f1a9-e9e4-4791-ace9-94acff87d48b
  ports:
  - name: http
    port: 8081
    protocol: TCP
