apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app.kubernetes.io/component":"sem-csmf","app.kubernetes.io/instance":"trisla","app.kubernetes.io/name":"trisla","app.kubernetes.io/version":"v3.7.29"},"name":"trisla-sem-csmf","namespace":"trisla"},"spec":{"ports":[{"name":"http","port":8080,"protocol":"TCP","targetPort":"http"}],"selector":{"app":"trisla-sem-csmf","app.kubernetes.io/instance":"trisla","app.kubernetes.io/name":"trisla"},"type":"ClusterIP"}}
    meta.helm.sh/release-name: trisla
    meta.helm.sh/release-namespace: trisla
  creationTimestamp: "2025-12-19T17:28:59Z"
  labels:
    app.kubernetes.io/component: sem-csmf
    app.kubernetes.io/instance: trisla
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: trisla
    app.kubernetes.io/version: v3.7.29
  name: trisla-sem-csmf
  namespace: trisla
  resourceVersion: "865815402"
  uid: b78eed2b-ec79-46e7-9606-b370556c097a
spec:
  clusterIP: 10.233.13.160
  clusterIPs:
  - 10.233.13.160
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: http
  selector:
    app: trisla-sem-csmf
    app.kubernetes.io/instance: trisla
    app.kubernetes.io/name: trisla
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
