apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app.kubernetes.io/component":"decision-engine","app.kubernetes.io/instance":"trisla","app.kubernetes.io/name":"trisla","app.kubernetes.io/version":"v3.7.29"},"name":"trisla-decision-engine","namespace":"trisla"},"spec":{"ports":[{"name":"http","port":8082,"protocol":"TCP","targetPort":"http"}],"selector":{"app":"trisla-decision-engine","app.kubernetes.io/instance":"trisla","app.kubernetes.io/name":"trisla"},"type":"ClusterIP"}}
    meta.helm.sh/release-name: trisla
    meta.helm.sh/release-namespace: trisla
  creationTimestamp: "2025-12-19T17:28:59Z"
  labels:
    app.kubernetes.io/component: decision-engine
    app.kubernetes.io/instance: trisla
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: trisla
    app.kubernetes.io/version: v3.7.29
  name: trisla-decision-engine
  namespace: trisla
  resourceVersion: "865815393"
  uid: d6dcdd8c-3d8b-4abf-90e1-bd3f8c26fe36
spec:
  clusterIP: 10.233.26.201
  clusterIPs:
  - 10.233.26.201
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 8082
    protocol: TCP
    targetPort: http
  selector:
    app: trisla-decision-engine
    app.kubernetes.io/instance: trisla
    app.kubernetes.io/name: trisla
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
