# ==========================================
# TriSLA - NASP Deployment Values
# ==========================================

backend:
  image: ghcr.io/abelisboa/trisla-api:latest
  service:
    port: 8000

frontend:
  image: ghcr.io/abelisboa/trisla-ui:latest
  service:
    port: 5173

nodeSelector:
  kubernetes.io/hostname: node1

service:
  type: NodePort
  ports:
    - name: backend
      port: 8000
      targetPort: 8000
      nodePort: 30800
    - name: frontend
      port: 5173
      targetPort: 80
      nodePort: 30173

resources:
  limits:
    cpu: "1"
    memory: "1Gi"
  requests:
    cpu: "0.5"
    memory: "512Mi"

tolerations:
  - key: "node-role.kubernetes.io/control-plane"
    operator: "Exists"
    effect: "NoSchedule"

replicaCount: 1

labels:
  app: trisla
annotations:
  maintainer: "TriSLA NASP Project (Abel Lisboa)"

imagePullSecrets:
  - name: ghcr-creds
