apiVersion: v1
kind: Endpoints
metadata:
  creationTimestamp: "2026-01-19T23:33:13Z"
  labels:
    app.kubernetes.io/component: ml-nsmf
    app.kubernetes.io/instance: trisla
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: trisla
    app.kubernetes.io/version: v3.7.29
  name: trisla-ml-nsmf
  namespace: trisla
  resourceVersion: "866080089"
  uid: 34e5c205-7101-4b12-a4f4-2f129367e269
subsets:
- addresses:
  - ip: 10.233.102.153
    nodeName: node1
    targetRef:
      kind: Pod
      name: trisla-ml-nsmf-d587bc8c9-j4sq2
      namespace: trisla
      uid: ff69bb04-a939-4e7a-b8a6-875228bb281f
  ports:
  - name: http
    port: 8081
    protocol: TCP
