apiVersion: v1
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJnaGNyLmlvIjogewoJCQkiYXV0aCI6ICJZV0psYkdselltOWhPbWRvY0Y5YVMyaHZSMlpuY1U5aU5rVnhTMnhKYmxSWlFuTlRRMWw2WmpkdWNFb3pVRUpMZDJVPSIKCQl9Cgl9Cn0K
kind: Secret
metadata:
  creationTimestamp: "2026-01-22T01:32:21Z"
  name: ghcr-secret
  namespace: trisla
  resourceVersion: "866472852"
  uid: 23500902-bd2f-4d77-8691-4eacf96e0247
type: kubernetes.io/dockerconfigjson
