apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: "2025-12-19T17:28:59Z"
  name: default
  namespace: trisla
  resourceVersion: "858270128"
  uid: 0d0de348-065d-4608-8cf9-b7b991aba4d3
