all:
  hosts:
    node1:
      ansible_host: 192.168.10.16
      ansible_user: porvir5g
    node2:
      ansible_host: 192.168.10.17
      ansible_user: porvir5g
  vars:
    ansible_python_interpreter: /usr/bin/python3
