apiVersion: apps/v1
kind: Deployment
metadata:
  name: trisla-rq-worker
  namespace: trisla
  labels:
    app: trisla-rq-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trisla-rq-worker
  template:
    metadata:
      labels:
        app: trisla-rq-worker
    spec:
      imagePullSecrets:
        - name: ghcr-creds
      containers:
        - name: rq-worker
          image: "trisla/api:latest"
          imagePullPolicy: IfNotPresent
          command: ["python3", "-m", "jobs.worker"]
          env:
            - name: REDIS_HOST
              value: "trisla-portal.trisla.svc.cluster.local"
            - name: REDIS_PORT
              value: "6379"
          resources:
            limits:
              cpu: "0.5"
              memory: "512Mi"
            requests:
              cpu: "0.2"
              memory: "256Mi"
