apiVersion: v1
kind: Endpoints
metadata:
  creationTimestamp: "2025-12-19T17:28:59Z"
  labels:
    app.kubernetes.io/component: decision-engine
    app.kubernetes.io/instance: trisla
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: trisla
    app.kubernetes.io/version: v3.7.29
  name: trisla-decision-engine
  namespace: trisla
  resourceVersion: "866130517"
  uid: 015d8d81-5665-47d0-8f53-cb73ef728b59
subsets:
- addresses:
  - ip: 10.233.102.168
    nodeName: node1
    targetRef:
      kind: Pod
      name: trisla-decision-engine-6fbf996cfb-rk4g5
      namespace: trisla
      uid: c9e6270d-3b50-42fb-a84e-b35dddef670c
  ports:
  - name: http
    port: 8082
    protocol: TCP
