apiVersion: v1
kind: Endpoints
metadata:
  creationTimestamp: "2025-12-19T17:28:59Z"
  labels:
    app.kubernetes.io/component: decision-engine
    app.kubernetes.io/instance: trisla
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: trisla
    app.kubernetes.io/version: v3.7.29
  name: trisla-decision-engine
  namespace: trisla
  resourceVersion: "866115402"
  uid: 015d8d81-5665-47d0-8f53-cb73ef728b59
subsets:
- addresses:
  - ip: 10.233.102.184
    nodeName: node1
    targetRef:
      kind: Pod
      name: trisla-decision-engine-6fbf996cfb-dkpnn
      namespace: trisla
      uid: 8fc5a1d8-93d7-48f4-a03a-322f7807487e
  ports:
  - name: http
    port: 8082
    protocol: TCP
