apiVersion: v1
kind: Endpoints
metadata:
  creationTimestamp: "2026-01-20T11:58:46Z"
  labels:
    app: besu
    app.kubernetes.io/component: trisla
    app.kubernetes.io/instance: trisla
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: trisla
    app.kubernetes.io/version: v3.7.29
    component: blockchain
  name: trisla-besu
  namespace: trisla
  resourceVersion: "866077568"
  uid: f3cfb894-d9b4-4406-84c8-47521cd06d98
subsets:
- addresses:
  - ip: 10.233.75.24
    nodeName: node2
    targetRef:
      kind: Pod
      name: trisla-besu-5d9454c8f8-gf8c7
      namespace: trisla
      uid: b9defbb9-e9ce-4f97-a584-490a0242152a
  ports:
  - name: p2p
    port: 30303
    protocol: TCP
  - name: rpc-ws
    port: 8546
    protocol: TCP
  - name: rpc
    port: 8545
    protocol: TCP
