apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: trisla
    meta.helm.sh/release-namespace: trisla
  creationTimestamp: "2025-12-19T17:28:59Z"
  labels:
    app.kubernetes.io/component: bc-nssmf
    app.kubernetes.io/instance: trisla
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: trisla
    app.kubernetes.io/version: v3.7.29
  name: trisla-bc-nssmf
  namespace: trisla
  resourceVersion: "866080636"
  uid: d723da61-20b3-4028-92bc-9e790001f21c
spec:
  clusterIP: 10.233.39.215
  clusterIPs:
  - 10.233.39.215
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 8083
    protocol: TCP
    targetPort: http
  selector:
    app: trisla-bc-nssmf
    app.kubernetes.io/instance: trisla
    app.kubernetes.io/name: trisla
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
