apiVersion: v1
kind: Endpoints
metadata:
  creationTimestamp: "2025-12-19T17:28:59Z"
  labels:
    app.kubernetes.io/component: decision-engine
    app.kubernetes.io/instance: trisla
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: trisla
    app.kubernetes.io/version: v3.7.29
  name: trisla-decision-engine
  namespace: trisla
  resourceVersion: "866080271"
  uid: 015d8d81-5665-47d0-8f53-cb73ef728b59
subsets:
- addresses:
  - ip: 10.233.102.158
    nodeName: node1
    targetRef:
      kind: Pod
      name: trisla-decision-engine-799b6c44f4-dw97g
      namespace: trisla
      uid: 2bdbbfb8-d7e3-4ce2-9275-20c5d024bce8
  ports:
  - name: http
    port: 8082
    protocol: TCP
