apiVersion: v1
kind: Endpoints
metadata:
  creationTimestamp: "2025-12-19T17:28:59Z"
  labels:
    app.kubernetes.io/component: sem-csmf
    app.kubernetes.io/instance: trisla
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: trisla
    app.kubernetes.io/version: v3.7.29
  name: trisla-sem-csmf
  namespace: trisla
  resourceVersion: "866080985"
  uid: e32b11ef-7b4f-4989-b3f9-66f8eacfe01c
subsets:
- addresses:
  - ip: 10.233.102.164
    nodeName: node1
    targetRef:
      kind: Pod
      name: trisla-sem-csmf-95dfc79f4-zpscg
      namespace: trisla
      uid: c0408c27-c08f-41b4-8909-2f22568596b0
  ports:
  - name: http
    port: 8080
    protocol: TCP
