apiVersion: v1
kind: Service
metadata:
  name: trisla-portal
  labels:
    app: trisla-portal
spec:
  type: {{ .Values.service.type | default "NodePort" }}
  selector:
    app: trisla-portal
  ports:
    - name: backend
      port: {{ .Values.backend.service.port | default 8000 }}
      targetPort: {{ .Values.backend.service.port | default 8000 }}
      nodePort: {{ (index .Values.service.ports 0).nodePort | default 30800 }}
      protocol: TCP
    - name: frontend
      port: {{ .Values.frontend.service.port | default 5173 }}
      targetPort: 80
      nodePort: {{ (index .Values.service.ports 1).nodePort | default 30173 }}
      protocol: TCP
